---
act_install_dependencies: true
act_user: act_runner
act_user_group: act_runner
act_user_additional_groups: ''
act_user_home: /home/{{ act_user }}

act_bin_dir: /usr/local/bin
act_bin_owner: root
act_bin_owner_group: root

act_runner_version: "0.2.6"
act_download_dir_url: "https://dl.gitea.com/act_runner/{{ act_runner_version }}"

act_gitea_config_path: /etc/gitea/gitea.ini
act_do_register: false
act_scope: ''

act_gitea_host: gitea.example.com
act_gitea_become_user: root
act_gitea_bin: /usr/local/bin/gitea
