---
# file: act_runner_playbook.yml
- name: Example playbook to setup an act_runner instance
  hosts: act_runner.example.com
  gather_facts: false
  vars:
    act_gitea_host: gitea.example.com
    act_do_register: true

  pre_tasks:
    - name: Gather subset of facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"

  roles:
    - role: wzzrd.gitea.act
