---
# file: gitea_playbook.yml
- name: Example playbook to setup a gitea instance
  hosts: gitea.example.com
  gather_facts: false
  vars:
    gitea_http_listen: "{{ ansible_facts.all_ipv4_addresses[0] }}"

  pre_tasks:
    - name: Gather subset of facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"

  roles:
    - role: wzzrd.gitea.gitea
