---
gitea_version: "1.21.4"
gitea_version_check: true
gitea_dl_url: "https://github.com/go-gitea/gitea/releases/download/v{{ gitea_version }}/gitea-{{ gitea_version }}-linux-{{ gitea_arch }}"
gitea_gpg_key: "7C9E68152594688862D62AF62D9AE806EC1592E2"
gitea_gpg_server: "hkp://keyserver.ubuntu.com:80"
gitea_backup_location: /var/backups/gitea
gitea_do_backup: false
gitea_systemd_cap_net_bind_service: false

gitea_app_name: "Gitea"
gitea_user: "gitea"
gitea_group: "gitea"
gitea_shell: "/bin/false"
gitea_home: "/var/lib/gitea"
gitea_repository_root: "{{ gitea_home }}"

gitea_http_domain: "localhost"
gitea_http_port: "3000"
gitea_http_host: "127.0.0.1"
gitea_root_url: "http://{{ gitea_http_domain }}:{{ gitea_http_port }}"

gitea_config_file:
  DEFAULT:
    APP_NAME: "Gitea: Git with a cup of tea"
    RUN_USER: "{{ gitea_user }}"
    WORK_PATH: "/usr/local/bin"
  server:
    APP_DATA_PATH: "{{ gitea_home }}/data"
    DOMAIN: "{{ gitea_http_domain }}"
    ROOT_URL: "{{ gitea_root_url }}"
    HTTP_ADDR: "{{ gitea_http_host }}"
    HTTP_PORT: "{{ gitea_http_port }}"
    START_SSH_SERVER: "false"
  database:
    DB_TYPE: "sqlite3"
  security:
    INSTALL_LOCK: "true"
    SECRET_KEY_URI: "file:/etc/gitea/secret_key"
    INTERNAL_TOKEN_URI: "file:/etc/gitea/internal_token"
  oauth2:
    ENABLED: "false"
  service:
    DISABLE_REGISTRATION: "true"
    REQUIRE_SIGNIN_VIEW: "true"
    ENABLE_NOTIFY_MAIL: "false"
    SHOW_REGISTRATION_BUTTON: "false"
  repository:
    ROOT: "{{ gitea_home }}"
  ui:
    SHOW_USER_EMAIL: "false"
    DEFAULT_THEME: "gitea-auto"
    THEMES: "gitea-auto,gitea-light,gitea-dark"
