- name: Prepare containers for molecule tests
  hosts: all
  gather_facts: false
  tasks:
    - name: Install xz for during tests
      ansible.builtin.package:
        name: xz
        state: present
