---
act_install_dependencies: true
act_runner_user: act_runner
act_runner_user_group: act_runner
act_runner_user_additional_groups: ''
act_runner_dir: /home/{{ act_runner_user }}

act_runner_bin_dir: /usr/local/bin
act_runner_bin_owner: root
act_runner_bin_owner_group: root

act_runner_version: "0.2.6"
act_runner_download_dir_url: "https://dl.gitea.com/act_runner/{{ act_runner_version }}"

gitea_server_config_path: /etc/gitea/gitea.ini
act_runner_do_register: false
act_runner_scope: ''

gitea_server: gitea.example.com
gitea_server_become_user: root
gitea_server_bin: /usr/local/bin/gitea
