---
- name: Create backup directory
  ansible.builtin.file:
    path: "{{ gitea_backup_location }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0750"

- name: Backing up gitea before upgrade
  ansible.builtin.command:
    cmd: >-
      /usr/local/bin/gitea dump -c /etc/gitea/gitea.ini
        --skip-lfs-data
        --skip-attachment-data
        --skip-package-data
    chdir: "{{ gitea_backup_location }}"
  become: true
  become_user: "{{ gitea_user }}"
  changed_when: true
