---
- name: Create internal token file based on variable
  ansible.builtin.copy:
    dest: /etc/gitea/internal_token
    content: "{{ gitea_internal_token }}"
    mode: "0600"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
  when: gitea_internal_token is defined

- name: Create internal file based on gitea generate output
  when: gitea_internal_token is undefined
  block:
    - name: Generate internal token with gitea generate secret INTERNAL_TOKEN
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          /usr/local/bin/gitea generate secret INTERNAL_TOKEN \
          > /etc/gitea/internal_token
        creates: /etc/gitea/internal_token
      args:
        executable: /usr/bin/bash

    - name: Set permissions on internal token file
      ansible.builtin.file:
        path: /etc/gitea/internal_token
        mode: "0600"
        owner: "gitea"
        group: "gitea"

- name: Create dictionary to hold internal_token uri
  ansible.builtin.set_fact:
    internal_token_dict:
      security:
        INTERNAL_TOKEN_URI: file:/etc/gitea/internal_token

- name: Combine config dictionary with internal_token_dict
  ansible.builtin.set_fact:
    gitea_config_file: "{{ gitea_config_file | combine(internal_token_dict, recursive=true) }}"
