---
- name: Create lfs jwt secret key file based on variable
  ansible.builtin.copy:
    dest: /etc/gitea/lfs_jwt_secret
    content: "{{ gitea_lfs_jwt_secret }}"
    mode: "0600"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
  when: gitea_lfs_jwt_secret is defined

- name: Create lfs jwt secret file based on gitea generate output
  when: gitea_lfs_jwt_secret is undefined
  block:
    - name: Generate lfs jwt secret with gitea generate secret LFS_JWT_SECRET
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          /usr/local/bin/gitea generate secret LFS_JWT_SECRET \
          > /etc/gitea/lfs_jwt_secret
        creates: /etc/gitea/lfs_jwt_secret
      args:
        executable: /usr/bin/bash

    - name: Set permissions on lfs jwt secret file
      ansible.builtin.file:
        path: /etc/gitea/lfs_jwt_secret
        mode: "0600"
        owner: "gitea"
        group: "gitea"

- name: Create dictionary to hold lfs_jwt_secret uri
  ansible.builtin.set_fact:
    lfs_jwt_secret_dict:
      server:
        LFS_JWT_SECRET_URI: file:/etc/gitea/lfs_jwt_secret

- name: Combine config dictionary with lfs_jwt_secret dict
  ansible.builtin.set_fact:
    gitea_config_file: "{{ gitea_config_file | combine(lfs_jwt_secret_dict, recursive=true) }}"
