---
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: Check gitea version yoz
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      /usr/local/bin/gitea -v | cut -d ' ' -f 3
  args:
    executable: /usr/bin/bash
  register: gitea_active_version
  changed_when: false
  failed_when: false
  when: gitea_version_check|bool

- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml

- name: Include user creation tasks
  ansible.builtin.include_tasks: create_user.yml

- name: Create config directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0755"
  loop:
    - /etc/gitea

- name: Create data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0750"
  loop:
    - "{{ gitea_home }}"
    - "{{ gitea_home }}/data"
    - "{{ gitea_home }}/custom"
    - "{{ gitea_home }}/custom/https"
    - "{{ gitea_home }}/custom/mailer"
    - "{{ gitea_home }}/indexers"
    - "{{ gitea_home }}/log"
    - "{{ gitea_repository_root }}"

- name: Include systemd installation tasks
  ansible.builtin.include_tasks: install_systemd.yml
  when: ansible_service_mgr == "systemd"

- name: Include secret key generation tasks
  ansible.builtin.include_tasks: secret_key.yml

- name: Include secret key generation tasks
  ansible.builtin.include_tasks: internal_token.yml

- name: Include oauth2 jwt secret generation tasks
  ansible.builtin.include_tasks: oauth2_jwt_secret.yml

- name: Include lfs jwt secret generation tasks
  ansible.builtin.include_tasks: lfs_jwt_secret.yml
  when:
    - gitea_config_file.server.LFS_START_SERVER is defined
    - gitea_config_file.server.LFS_START_SERVER == "true"

- name: Configure gitea
  ansible.builtin.copy:
    content: "{{ gitea_config_file | community.general.to_ini }}"
    dest: /etc/gitea/gitea.ini
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0600"
  notify: Restart gitea

- name: Service gitea
  ansible.builtin.service:
    name: gitea
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"
