---
- name: Create jwt secret key file based on variable
  ansible.builtin.copy:
    dest: /etc/gitea/oauth2_jwt_secret
    content: "{{ gitea_oauth2_jwt_secret }}"
    mode: "0600"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
  when: gitea_oauth2_jwt_secret is defined

- name: Create oauth2 jwt secret file based on gitea generate output
  when: gitea_oauth2_jwt_secret is undefined
  block:
    - name: Generate oauth2 jwt secret file with generate secret JWT_SECRET
      ansible.builtin.shell: |
        cmd: |
          set -o pipefail && \
          /usr/local/bin/gitea generate secret JWT_SECRET \
        > /etc/gitea/oauth2_jwt_secret
      args:
        creates: /etc/gitea/oauth2_jwt_secret

    - name: Set permissions on oauth2 jwt secret file
      ansible.builtin.file:
        path: /etc/gitea/oauth2_jwt_secret
        mode: "0600"
        owner: "gitea"
        group: "gitea"

- name: Create dictionary to hold oauth_jwt_secret uri
  ansible.builtin.set_fact:
    oauth_jwt_secret_dict:
      oauth2:
        JWT_SECRET_URI: file:/etc/gitea/oauth2_jwt_secret

- name: Combine config dictionary with oauth_jwt_secret dict
  ansible.builtin.set_fact:
    gitea_config_file: "{{ gitea_config_file | combine(oauth_jwt_secret_dict, recursive=true) }}"
