---
- name: Create secret key file based on variable
  ansible.builtin.copy:
    dest: /etc/gitea/secret_key
    content: "{{ gitea_secret_key }}"
    mode: "0600"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
  when: gitea_secret_key is defined

- name: Create secret key file based on gitea generate output
  when: gitea_secret_key is undefined
  block:
    - name: Generate secret key with gitea generate secret SECRET_KEY
      ansible.builtin.shell: |
        cmd: |
          set -o pipefail && \
          /usr/local/bin/gitea generate secret SECRET_KEY \
        > /etc/gitea/secret_key
      args:
        creates: /etc/gitea/secret_key

    - name: Set permissions on secret key file
      ansible.builtin.file:
        path: /etc/gitea/secret_key
        mode: "0600"
        owner: "gitea"
        group: "gitea"

- name: Create dictionary to hold secret_key uri
  ansible.builtin.set_fact:
    secret_key_dict:
      security:
        SECRET_KEY_URI: file:/etc/gitea/secret_key

- name: Combine config dictionary with secret_key_dict
  ansible.builtin.set_fact:
    gitea_config_file: "{{ gitea_config_file | combine(secret_key_dict, recursive=true) }}"
