- name: Fail if runner or server groups are missing
  hosts: localhost
  tasks:
    - name: Assert group existence
      ansible.builtin.assert:
        that:
          - "'runners' in groups"
          - "'servers' in groups"
        fail_msg: |
          runners or servers group was not found inside inventory groups: {{ groups }}

- name: Converge servers
  hosts: servers
  gather_facts: false
  vars:
    gitea_db_type: sqlite3
  pre_tasks:
    - name: Gather required subset of facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - default_ipv4

  roles:
    - role: gitea
      vars:
        gitea_http_host: "{{ ansible_facts.all_ipv4_addresses[0] }}"
        gitea_http_domain: "{{ ansible_hostname }}"

- name: Converge
  hosts: runners
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false
  vars:
    act_gitea_host: "{{ inventory_hostname|split('_')|first }}_server"
    act_gitea_host_port: 3000
    act_gitea_host_protocol: http
    act_gitea_become_user: gitea
    act_gitea_bin: /usr/local/bin/gitea
    act_gitea_config_path: /etc/gitea/gitea.ini
    act_do_register: true
  pre_tasks:
    - name: Gather required subset of facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
  roles:
    - role: act
