- name: Prepare servers for molecule tests
  hosts: servers
  gather_facts: false
  connection: community.okd.oc
  tasks:
    - name: Install sudo for during tests
      ansible.builtin.dnf:
        name: sudo
        state: present
