---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: ubi8
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_built_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: "/usr/sbin/init"
    platform: linux/amd64
  - name: ubi9
    image: registry.access.redhat.com/ubi9/ubi-init
    pre_built_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: "/usr/sbin/init"
    platform: linux/amd64
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency                                                                                                      - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
