- name: Verify
  hosts: all
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false

  tasks:
    - name: Check if git is installed
      block:
        - name: Check for install status of git package
          ansible.builtin.package:
            name: git
            state: installed
          register: git_package_status

        - name: Verify result of previous task
          ansible.builtin.assert:
            that:
              - not git_package_status.changed

    - name: Check if gitea binary exists
      block:
        - name: Check for existence for /usr/local/bin/gitea
          ansible.builtin.stat:
            path: /usr/local/bin/gitea
          register: gitea_stat_result

        - name: Verify result of previous task
          ansible.builtin.assert:
            that:
              - gitea_stat_result.stat.exists

    - name: Check if gitea service is running
      block:
        - name: Gather service facts
          ansible.builtin.service_facts:

        - name: Verify result of previous task
          ansible.builtin.assert:
            that:
              - ansible_facts.services['gitea.service'] is defined
              - ansible_facts.services['gitea.service']['state'] == "running"
              - ansible_facts.services['gitea.service']['status'] == "enabled"

    - name: Check if gitea configfile exists
      block:
        - name: Check for existence of /etc/gitea/gitea.ini
          ansible.builtin.stat:
            path: /etc/gitea/gitea.ini
          register: gitea_config_stat_result

        - name: Verify result of previous task
          ansible.builtin.assert:
            that:
              - gitea_config_stat_result.stat.exists
