name: Lint, test and tag

on: push

jobs:
  lint-all-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v24.2.0

  molecule-act-default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Run molecule tests for act role
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ${{ github.repository }}/roles/act
          molecule_args: --driver-name docker
        env:
          ANSIBLE_FORCE_COLOR: '1'

  molecule-act-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Run molecule update tests for act role
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ${{ github.repository }}/roles/act
          molecule_args: --driver-name docker -s update
        env:
          ANSIBLE_FORCE_COLOR: '1'

  molecule-gitea-default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Run molecule tests for gitea role
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ${{ github.repository }}/roles/gitea
          molecule_args: --driver-name docker
        env:
          ANSIBLE_FORCE_COLOR: '1'

  molecule-gitea-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Run molecule tests for gitea role
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ${{ github.repository }}/roles/gitea
          molecule_args: --driver-name docker -s update
        env:
          ANSIBLE_FORCE_COLOR: '1'

  molecule-gitea-and-act:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Run molecule tests for act and gitea roles together
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ${{ github.repository }}
          molecule_args: --driver-name docker
        env:
          ANSIBLE_FORCE_COLOR: '1'

  tag-new-versions:
    runs-on: ubuntu-latest
    needs:
      - molecule-act-default
      - molecule-act-update
      - molecule-gitea-default
      - molecule-gitea-update
      - molecule-gitea-and-act
      - lint-all-files
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            awk ' /version: /  { print $2 } ' galaxy.yml | tr -d '"'
